GRANT ALL PRIVILEGES ON DATABASE mads_swap TO nick;
GRANT ALL PRIVILEGES ON DATABASE mads_swap TO soph;
GRANT ALL PRIVILEGES ON DATABASE mads_swap TO tim;
GRANT ALL PRIVILEGES ON DATABASE mads_swap TO binance_crawler;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO nick;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO soph;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO tim;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO binance_crawler;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nick;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO soph;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO tim;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO binance_crawler;